addpath('../libsvm/matlab/');
addpath('./utils/');
addpath('./core_functions/');
clear;

datasets = {
'iris', ...
% 'wine', ...
% 'glass', ...
% 'svmguide2', ...
% 'vowel', ...
% 'vehicle', ...
% 'dna', ...
% 'segment', ...
% 'satimage', ...
% 'usps', ...
% 'pendigits', ...
% 'letter', ...
% 'protein', ...
% 'poker', ...
% 'shuttle', ...
% 'Sensorless', ...
% 'mnist', ...
};

model.n_folds = 5;
model.n_repeats = 30;
model.rate_test = 0.3;
model.rate_labeled = 0.3;
model.n_batch = 1;
model.T = 50;
model.can_tau_I = [10.^(-9:-7), 0];
model.can_tau_A = 10.^-(7:2:11);
model.can_tau_S = [10.^-(3:2:7), 0];
model.can_step = 10.^(3:4);
